/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IconCarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    IconEmojioneV1TopHat: typeof import('~icons/emojione-v1/top-hat')['default']
    LazyLoading: typeof import('./src/components/lazy-loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/Test.vue')['default']
  }
}
